AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy an RDS instance in a private subnet

Parameters:
  VpcId:
    Type: String
    Description: The ID of your existing VPC
  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The IDs of your existing private subnets

Resources:
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS
      VpcId: !Ref VpcId

  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds: !Ref PrivateSubnetIds

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      Engine: mysql  
      EngineVersion: 5.7
      MasterUsername: admin
      MasterUserPassword: Password123! 
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      DBSubnetGroupName: !Ref RDSSubnetGroup
      MultiAZ: false
      PubliclyAccessible: false 

Outputs:
  RDSInstanceEndpoint:
    Description: Endpoint for the RDS instance
    Value: !GetAtt RDSInstance.Endpoint.Address
